name: Run tests

on: [pull_request, push]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - run: julia -e 'using Pkg; Pkg.instantiate(); Pkg.add(url="https://github.com/Qaintum/Qaintessent.jl", rev="master")'
      - uses: julia-actions/julia-runtest@master
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1

