name: Run tests

on: [pull_request, push]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - run: julia --project test/installQaintessent.jl
      - uses: julia-actions/julia-runtest@master
